Fixes Telescope #2134: Move Elastic client to Satellite
Seneca-CDOT/satellite pull request #13
Opened 2021-04-13 01:32 UTC by HyperTHD

This PR refactors the elastic client code from Telescope into Satellite. This fulfills PR [#2134](https://github.com/Seneca-CDOT/telescope/issues/2134).

Currently working on the tests, should soon be ready for review

2021-04-13 18:42 UTC, humphd requested changes

2021-04-13 18:42 UTC, humphd commented on src/elastic.js
> +      path: '/posts/post/:post_id',
`path: '*',`

2021-04-13 18:42 UTC, humphd commented on src/elastic.js
> +function createElasticClient() {
Let's allow passing in options here, and pass them through:

```js
function createElasticClient(options = {}) {
  const elasticUrl = `${ELASTIC_URL}:${ELASTIC_PORT}`;
  return new ElasticConstructor({ ...options, node: elasticUrl });
}
```

2021-04-15 13:23 UTC, humphd requested changes

2021-04-15 13:23 UTC, humphd commented on src/elastic.js
> +  const client = new Client(options);
I think you need to do what the mock client does with Elastic to set the mock connection on options:

```js
const { Client } = require('@elastic/elasticsearch')
const Mock = require('@elastic/elasticsearch-mock')
 
const mock = new Mock()
const client = new Client({
  node: 'http://localhost:9200',
  Connection: mock.getConnection()
})
```

2021-04-15 13:23 UTC, humphd commented on test.js
> +    elastic.info(console.log);
Assert the values that `elastic.info()` produces vs passing to console.log

2021-04-15 13:23 UTC, humphd commented on test.js
> +    done();
Unless you're inside a callback (which you might want to be with my change above), you don't need `done()` in sync paths.

2021-04-16 18:52 UTC, humphd requested changes
Excellent.  Please update the README with details about this, matching what we do there now for Redis.

2021-04-16 19:19 UTC, humphd approved these changes

2021-04-18 20:43 UTC, Metropass approved these changes

2021-04-18 21:37 UTC, merged

2021-04-18 21:39 UTC, humphd commented
I've tagged v1.13.0 to include this, which is building now.