Adding ES error cases to createError
Seneca-CDOT/satellite pull request #64
Opened 2022-02-19 04:35 UTC by rclee91

Follow up of #63 

Gave createError its own module so we could add cases for ElasticSearch errors.
Updated the tests to reflect the changes as well. 

To test: `pnpm test`

For this change, the ES error will be created into an `http-error` indirectly first, before being sent into `createError` again as a nested error with additional props. 
Doing so this way, we get to keep the ES error `statusCode`, it won't be overwritten. 
However, I have no way of changing the description name of the final error to whatever ES might have named the specific status code to. The names are based on the `status` code that `createError` receives.
For example, a `404` status code will always be created as a  `NotFoundError`, as shown below
```js
    const elasticError = new errors.ResponseError({
      body: { error: 'testing ElasticSearch Error' },
      statusCode: 404,
    });

    const testESError = createError(503, elasticError);
    console.log(testESError);
```
The log would be something like
```text
 NotFoundError: ElasticSearch Error:ResponseError
        at ... {
      body: { error: 'testing ElasticSearch Error' }
    }
```
So, it might be up for discussion if we want to keep the ES error status codes, or if we have it so they can be overwritten.

2022-02-23 19:45 UTC, humphd requested changes

2022-02-23 19:45 UTC, humphd commented on src/createError.js
> +module.exports.createError = (...args) => {
`module.exports = (...args) => {`

2022-02-23 19:45 UTC, humphd commented on src/createError.js
> +    if (type === 'object' && arg instanceof errors.ResponseError) {
Add comments please to indicate what each path is doing in this if.

2022-02-23 19:45 UTC, humphd commented on src/index.js
> +module.exports.createError = require('./createError').createError;
`module.exports.createError = require('./create-error');`

NOTE: always name files in lower-case, since not all filesystems are case sensitive.

2022-02-23 19:45 UTC, humphd commented on src/createError.js
> +const _createError = require('http-errors');
Rename this file to `src/create-error.js`

2022-02-24 23:09 UTC, rclee91 commented
Changed the file name, added comments, and changed the `module.exports` line. 
I've also added a new test to show cases where a status code is not included as the first argument.
http-errors will set the status to 500 in such cases.
```js
  test('errors created without a status code should return a status of 500', () => {
    expect(createError('testing').status).toBe(500);
  });
```

2022-02-25 20:11 UTC, humphd approved these changes

2022-02-25 20:17 UTC, AmasiaNalbandian approved these changes

2022-02-25 20:25 UTC, merged