Complete Port of our Redis.js onto Satellite
Seneca-CDOT/satellite pull request #7
Opened 2021-03-16 20:00 UTC by Metropass

In issue [#1908](https://github.com/Seneca-CDOT/telescope/issues/1908), we discussed about porting Redis onto Satellite for use on other modules.

Everything here should work (in theory), but I need some help on writing tests for Redis.

2021-03-16 20:01 UTC, Metropass commented on src/redis.js
> +    //createError(error, message); Future Proofing when createError is merged.
I left this commented out, until createError is merged. Once that happens, I'll be using that instead of throwing an Error.

2021-03-16 20:10 UTC, c3ho commented
What tests are you trying to write?

2021-03-16 20:18 UTC, Metropass commented
> What tests are you trying to write?

Just a simple test that makes sure that Redis and MockRedis are working as expected

2021-03-16 20:19 UTC, c3ho commented
I'm assuming you're just checking for connectivity then?

2021-03-16 21:21 UTC, Metropass commented
> I'm assuming you're just checking for connectivity then? If so, Redis has a PING command, if it is connected should return PONG https://redis.io/commands/PING

Noted, thanks! I'll add that in `test.js`

2021-03-17 19:17 UTC, humphd commented
This needs a rebase.

2021-03-19 23:48 UTC, Metropass commented
@humphd I might have to move the Redis test onto Telescope instead of Satellite. I need to have Docker running within Telescope to get the tests to pass.

2021-03-20 00:50 UTC, Metropass commented
Yup, just tested it. If we try to bring Redis onto our tests, it will continue to run until we explicitly kill it. Should we add a function that will allow us to terminate the process?

2021-03-20 16:37 UTC, humphd requested changes

2021-03-20 16:37 UTC, humphd commented on package.json
> +    "array-from": "^2.1.1",
Unused, please remove this.

2021-03-20 16:37 UTC, humphd commented on src/redis.js
> +  redis: createRedisClient(),
This is why you're having tests not finish, due to open connections.  Let's change the exports:

```js
module.exports = createRedisClient()
```

And in `index.js` let's expose it on Satellite like this:

```js
module.exports.Redis = require('./src/redis')`
```

This way anyone who wants to use Redis in a microservice would do this:

```js
const { Redis }  = require('@senecacdot/satellite');
...
const redis = Redis();
// use redis...
...
// when shutting down, disconnect the redis client to close connections
redis.disconnect();
```

2021-03-20 16:37 UTC, humphd commented on src/redis.js
> +const redisUrl = 'http://redis:6379';
This seems wrong.  First, it's using `http://` vs. `redis://`, and second, it's not using an env variable.

2021-03-26 16:17 UTC, humphd commented
Has this stalled?

2021-03-31 13:14 UTC, humphd commented
@Metropass what's up with this PR?

2021-03-31 15:08 UTC, Metropass commented
> @Metropass what's up with this PR?

Had to postpone it for now, at least until I finish with my Cache middleware, and progress further with the CORS Middleware. ETA on that should be around 3 days

2021-03-31 19:53 UTC, humphd commented
When this goes in, remind me that we need to use it in the Auth service to do Redis backed sessions.

2021-04-09 16:50 UTC, HyperTHD commented
#11 successfully ports redis to Satellite. Closing this PR

2021-04-09 16:50 UTC, closed without merging